export const MOCK_PRODUCTS = [
  {
    id: "p1",
    title: "AI Business Concierge & WhatsApp Automation Suite",
    description: "An enterprise-grade AI chatbot that autonomously manages your entire WhatsApp sales funnel, handling complex menu parsing, localized colloquialisms, and full payment processing without human intervention.",
    price: 149,
    category: "CHATBOT",
    rating: "4.9",
    reviews_count: 842,
    installs_count: 12000,
    setup_time: "Under 3 minutes",
    status: "active",
    image_url: "/whatsapp_orders_ai.png",
    demo_url: "https://example.com/demo/whatsapp",
    features: ["Advanced NLP Engine (GPT-4o)", "Frictionless Stripe integration", "50+ Languages & local dialects", "Zero-latency push notifications", "Customer CRM synchronization"],
    what_it_does: "Completely replaces human SDRs and hospitality staff on WhatsApp. The bot understands extreme nuances in orders, handles modifications, collects shipping data, and secures payments natively inside the WhatsApp interface.",
    who_its_for: ["Multi-location Restaurants", "Luxury E-commerce Brands", "High-volume Local Services", "DTC Retailers"],
    whats_included: ["Pre-trained AI Brain", "Meta Developer API Setup", "Real-time Analytics Dashboard", "Custom Brand Voice Tuning"],
    whats_not_included: ["WhatsApp Business API usage fees", "Stripe transaction fees", "Custom hardware integrations"],
    delivery_info: "Proprietary model weights and API keys delivered instantly. Activation within 180 seconds."
  },
  {
    id: "p2",
    title: "Neural Support System Level III",
    description: "Slash your customer support overhead by 85% with an autonomous agent capable of resolving highly technical Tier 1 & 2 tickets, pulling directly from your live documentation and codebase.",
    price: 349,
    category: "AUTOMATION",
    rating: "4.9",
    reviews_count: 1024,
    installs_count: 4500,
    setup_time: "Under 15 minutes",
    status: "active",
    image_url: "/ai_customer_support.png",
    demo_url: "https://example.com/demo/support",
    features: ["Vector-database memory sync", "Zendesk & Intercom native hooks", "Automated empathy routing", "Multi-modal vision support (PDF/Images)"],
    what_it_does: "Ingests your entire company wiki, Slack history, and past tickets via RAG (Retrieval-Augmented Generation) to perfectly respond to any customer inquiry. It knows exactly when and how to escalate to human agents with a summarized context brief.",
    who_its_for: ["Fast-scaling SaaS", "Financial Institutions", "Enterprise Support Desks"],
    whats_included: ["Enterprise RAG Architecture", "Live Embedding Sync Pipeline", "Support Widget SDK", "White-glove Escalation Protocol"],
    whats_not_included: ["Base LLM token costs", "SLA guarantees for custom external APIs"],
    delivery_info: "Secure container deployment matrix sent instantly upon clearance."
  },
  {
    id: "p3",
    title: "Omnichannel Smart Booking Matrix",
    description: "A sophisticated neural scheduler that eliminates double bookings and calendar drift, leveraging predictive analytics to optimize your staff's daily utilization and maximize daily ROI.",
    price: 199,
    category: "AUTOMATION",
    rating: "4.8",
    reviews_count: 412,
    installs_count: 3200,
    setup_time: "Under 5 minutes",
    status: "active",
    image_url: "/smart_booking_ai.png",
    demo_url: "https://example.com/demo/booking",
    features: ["Predictive No-show Analysis", "Dynamic Surge Pricing", "Two-way Google/Outlook Sync", "Automated SMS/WhatsApp Reminders"],
    what_it_does: "Connects to your existing calendars and acts as an elite digital receptionist. Uses historical data to predict and prevent no-shows while dynamically adjusting prices during peak operational hours.",
    who_its_for: ["Premium Salons & Spas", "Private Health Clinics", "High-ticket Consultants", "Law Firms"],
    whats_included: ["Deep Calendar Integration", "Predictive Analytics Engine", "Custom Client Booking Portal", "Stripe Retainer Processing"],
    whats_not_included: ["Twilio SMS fees", "Domain hosting for custom portal"],
    delivery_info: "Instant platform access and synchronization keys via secure email."
  },
  {
    id: "p4",
    title: "Autonomous Social Growth Engine",
    description: "An AI-native content generation and distribution framework that analyzes viral trends sub-second and fabricates high-converting multimedia posts entirely on autopilot.",
    price: 299,
    category: "MARKETING",
    rating: "4.9",
    reviews_count: 655,
    installs_count: 8100,
    setup_time: "Under 10 minutes",
    status: "active",
    image_url: "/social_autoposter_ai.png",
    demo_url: "https://example.com/demo/marketing",
    features: ["Sub-second Trend Analysis", "AI Image & Video Generation", "Context-aware Hashtagging", "Cross-platform API Broadcasting"],
    what_it_does: "Continuously scans TikTok, X, and Instagram for emerging trends. It drafts, generates media, and schedules hyper-optimized posts matching your brand's archetype to capture massive organic reach.",
    who_its_for: ["E-commerce Brands", "Influencer Agencies", "Media Conglomerates", "Real Estate Brokers"],
    whats_included: ["Stable Diffusion / Midjourney pipelines", "Trend scraping algorithms", "Multi-tenant Scheduling Matrix"],
    whats_not_included: ["API overage costs for image generation", "Platform-specific ad budget"],
    delivery_info: "Automated provisioning of your isolated AI environment in seconds."
  },
  {
    id: "p5",
    title: "Predictive Inventory Oracle",
    description: "Connect your Shopify or ERP to our predictive neural network to forecast demand with 98% accuracy. Never overstock or sell out again.",
    price: 499,
    category: "ANALYTICS",
    rating: "5.0",
    reviews_count: 112,
    installs_count: 890,
    setup_time: "Under 20 minutes",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80",
    demo_url: "https://example.com/demo/inventory",
    features: ["Deep Learning Demand Forecasting", "Supply Chain Disruption Alerts", "Automated Purchase Order Drafting", "Shopify/Magento/WooCommerce Native"],
    what_it_does: "Ingests years of your sales data, weather patterns, and market trends to tell you exactly how many units of every SKU to order and precisely when to order them.",
    who_its_for: ["7-8 Figure E-commerce Brands", "Global Distributors", "Retail Chains"],
    whats_included: ["Oracle Forecasting Model", "ERP Integration Keys", "Real-time Disruption Alerts", "Automated Supplier Emails"],
    whats_not_included: ["Custom legacy ERP integration coding", "Data cleaning for corrupted historical data"],
    delivery_info: "Secure API gateway credentials supplied instantly."
  },
  {
    id: "p6",
    title: "AI-Powered SEO Architecture",
    description: "Dominates search algorithms by programmatically generating thousands of pillar pages, interconnected clusters, and hyper-optimized schemas faster than humanly possible.",
    price: 399,
    category: "WEBSITE",
    rating: "4.8",
    reviews_count: 531,
    installs_count: 4200,
    setup_time: "Under 5 minutes",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80",
    demo_url: "https://example.com/demo/seo",
    features: ["Programmatic Content Generation", "Automated Internal Linking Matrix", "Dynamic Schema Injection", "Real-time SERP Tracking"],
    what_it_does: "Constructs massive, highly valuable, and unique content silos that capture long-tail keywords. It builds an internal linking structure invisible to the eye but favored heavily by search engine crawlers.",
    who_its_for: ["Affiliate Marketers", "Content Agencies", "Directory Sites", "High-growth Startups"],
    whats_included: ["Semantic Keyword Mapper", "Automated Publisher Webhook", "Rank Tracking Dashboard"],
    whats_not_included: ["Premium Backlink Acquisition", "Manual Editorial Review"],
    delivery_info: "Webhook and API ecosystem architecture activated instantly."
  }
];

export const MOCK_CUSTOM_SOLUTIONS = [
  {
    id: "c1",
    title: "AI-Powered Business Website",
    description: "Get a professional, conversion-optimized website tailored specifically for your business in minutes. No coding required.",
    category: "WEBSITE",
    status: "active",
    price_min: 99,
    price_max: 299,
    rating: "4.9",
    installs_count: "342",
    delivery_days: 1,
    developer_name: "WebMind AI Lab",
    image_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80",
    what_it_does: "Builds a complete, blazing-fast web presence. The AI generates compelling copy, dynamic layouts, and optimizes for both mobile responsiveness and ultra-low latency loading speeds to maximize user conversion.",
    who_its_for: ["Small Business Owners", "Freelancers", "Local Contractors", "Startups"],
    whats_included: ["Custom Domain Setup", "SEO-optimized Copywriting", "SSL Certificate Setup", "Next.js Architecture", "30 Days Free Hosting"],
    whats_not_included: ["Custom graphic design creation", "Complex web3 integrations", "Ongoing monthly server costs"],
    customization_options: ["Branding Colors", "Typography Selection", "Custom Forms", "Booking System Integration"],
    features: ["Sub-second Loading", "Fully Responsive", "Dark Mode Native", "AI Copywriting"]
  },
  {
    id: "c2",
    title: "Automated Lead Capture & Follow-up",
    description: "Capture leads passively from your website and automatically orchestrate elaborate, highly-personalized follow-up sequences across Email and SMS.",
    category: "AUTOMATION",
    status: "active",
    price_min: 69,
    price_max: 149,
    rating: "4.8",
    installs_count: "178",
    delivery_days: 2,
    developer_name: "ConvertLogic",
    image_url: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&q=80",
    what_it_does: "We deploy an invisible pixel and interactive capture nodes on your current site. Once a lead engages, an AI-driven sequence drips highly personalized content designed to push them to book a call or checkout.",
    who_its_for: ["B2B Service Providers", "High-ticket Coaches", "Agencies"],
    whats_included: ["Lead Capture Form Injection", "3-month SMS/Email Sequence AI Generation", "CRM Synchronization Webhooks"],
    whats_not_included: ["Ad-spend management", "Twilio API costs", "Mailgun sending limits"],
    customization_options: ["Tone of voice", "Discount offer integration", "Lead routing rules"],
    features: ["Intelligent Drip Sequences", "A/B Testing Native", "Spam-trap Avoidance"]
  },
  {
    id: "c3",
    title: "Enterprise Knowledge Base Orchestrator",
    description: "Transform thousands of scattered PDFs, Word Docs, and Slack messages into a unified, queryable, secure LLM brain for your employees.",
    category: "ENTERPRISE",
    status: "active",
    price_min: 999,
    price_max: 2999,
    rating: "5.0",
    installs_count: "41",
    delivery_days: 7,
    developer_name: "Neural Nexus Enterprise",
    image_url: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&q=80",
    what_it_does: "Builds a highly secure, private instance of an AI model trained strictly on your internal proprietary data. Employees can ask it complex questions and receive instant, cited answers drawing from thousands of encrypted documents.",
    who_its_for: ["Law Firms", "Medical Researchers", "Fortune 500 HR Departments"],
    whats_included: ["SOC 2 Compliant Hosting architecture", "End-to-End Vectorization", "Custom Web Portal build", "Active Data Pipeline integration"],
    whats_not_included: ["On-premise hardware provisioning", "Historical data cleanup/OCR translation for handwritten docs"],
    customization_options: ["Role-based Access Controls (RBAC)", "UI/UX Whitelabeling", "Model Selection (Llama-3 vs Claude)"],
    features: ["Military-grade Encryption", "Zero Data Retention", "Source Citation"]
  },
  {
    id: "c4",
    title: "Cinematic Video Generator Agent",
    description: "A custom fine-tuned model wrapper that takes simple product shots and generates ultra-realistic, cinematic promotional video advertisements.",
    category: "MARKETING",
    status: "active",
    price_min: 249,
    price_max: 799,
    rating: "4.7",
    installs_count: "215",
    delivery_days: 3,
    developer_name: "StudioFusion",
    image_url: "https://images.unsplash.com/photo-1626544827763-d516dce335e2?w=600&q=80",
    what_it_does: "Uses advanced diffusion techniques (Sora/RunwayML architecture pipelines) configured specifically for your brand's aesthetic. Feed it a photo of your product, output a 15-second tracking shot advertising asset.",
    who_its_for: ["Digital Marketing Agencies", "Jewelry/Fashion E-commerce", "Car Dealerships"],
    whats_included: ["Custom Fine-tuned LoRA Model", "Video Rendering Infrastructure Setup", "API Access Endpoint"],
    whats_not_included: ["Cloud GPU render costs", "Human actor licensing fees"],
    customization_options: ["Aspect Ratio Matrix", "Brand Color Grading", "Audio Syncing"],
    features: ["4K Upscaling Native", "Temporal Consistency", "Commercial Usage Rights"]
  },
  {
    id: "c5",
    title: "Financial Ledger Anomaly Detector",
    description: "Integrate a mathematical AI agent directly into Quickbooks or Xero to autonomously audit every transaction passing through your accounts in real time.",
    category: "ANALYTICS",
    status: "active",
    price_min: 399,
    price_max: 999,
    rating: "4.9",
    installs_count: "88",
    delivery_days: 4,
    developer_name: "QuantSafe AI",
    image_url: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&q=80",
    what_it_does: "Acts as a ghost forensic accountant. Models standard spending behaviors and instantly flags fractional anomalies, duplicate invoicing, or erratic supplier pricing changes direct to your CFO's inbox.",
    who_its_for: ["Venture Backed Startups", "CFOs", "Accounting Firms", "Large Non-profits"],
    whats_included: ["API Integration with Xero/QBO", "Rule-based + LLM combined logic", "Executive Dashboard reporting"],
    whats_not_included: ["Legal remediation", "Tax filing services"],
    customization_options: ["Flagging thresholds", "Vendor whitelisting", "Report frequency"],
    features: ["Real-time Monitoring", "Receipt parsing", "Fraud pattern recognition"]
  },
  {
    id: "c6",
    title: "Smart Kitchen Display & Inventory System",
    description: "An AI-powered orchestration system for restaurant kitchens. Maps incoming orders dynamically to reduce prep times, whilst tracking ingredient burn-rates via vision AI.",
    category: "AUTOMATION",
    status: "active",
    price_min: 399,
    price_max: 799,
    rating: "4.8",
    installs_count: "156",
    delivery_days: 7,
    developer_name: "Gastronomic AI Core",
    image_url: "https://images.unsplash.com/photo-1547926839-4467bd541ecf?w=600&q=80",
    what_it_does: "Replaces traditional ticket-printing KDS. It analyzes average ticket time, parses complex modifications, and routes different prep components to separate stations ensuring dishes finish concurrently.",
    who_its_for: ["Ghost Kitchens", "High-volume Quick Service", "Fine Dining Establishments"],
    whats_included: ["Custom menu logic mapping", "KDS UI Installation package", "Kitchen Display setup", "90 days high-priority support"],
    whats_not_included: ["Hardware (Tablets/Printers)", "Third-party delivery integration overrides", "Monthly network maintenance"],
    customization_options: ["Station routing rules", "Display UI colors", "Prep-time override logic"],
    features: ["Concurrent Dish Timing", "Waste Tracking", "Automated 86'ing"]
  }
];
