export const MOCK_PRODUCTS = [
  {
    id: "p1",
    title: "AI Customer Support Bot",
    plain_english: "A bot that answers your customers' questions 24/7 — so you don't have to. It reads your FAQs and replies instantly.",
    description: "An autonomous, enterprise-grade support agent that seamlessly integrates with your existing helpdesk. It reads your entire knowledge base, past support tickets, and website content to instantly resolve Tier 1 and Tier 2 tickets. If a customer has a complex issue, the bot automatically escalates the conversation to a human agent along with a summary of the issue.",
    price: 149,
    category: "chatbot",
    rating: "4.9",
    reviews_count: 842,
    installs_count: 12000,
    setup_time: "Under 5 min",
    status: "active",
    badge: "Best Seller",
    image_url: "https://images.unsplash.com/photo-1587560699334-cc4ff634909a?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/support",
    features: ["GPT-4o Powered Architecture", "Native Zendesk & Intercom webhooks", "Smart Auto-escalation to human staff", "Real-time Multi-language translation"],
    what_it_does: "This AI ingests your entire help center, FAQs, and product manuals. When a customer reaches out via chat, email, or WhatsApp, it instantly analyzes their question and provides a perfectly accurate, human-like response. It can handle order tracking, refund requests, and general troubleshooting completely on its own without any human intervention.",
    who_its_for: ["Fast-growing SaaS companies needing 24/7 technical support coverage", "High-volume E-commerce stores dealing with repetitive 'where is my order' questions", "Service businesses looking to reduce their customer support payroll costs"],
    whats_included: ["Complete RAG (Retrieval-Augmented Generation) model setup", "Embeddable website chat widget SDK", "Comprehensive analytics dashboard to track bot performance", "30 days of priority technical support and fine-tuning"],
    whats_not_included: ["Ongoing AI token generation costs (billed directly via OpenAI)", "Custom backend API integrations beyond standard helpdesks"],
    delivery_info: "Instantly deployed to your workspace in under 5 minutes."
  },
  {
    id: "p2",
    title: "Restaurant Booking Assistant",
    plain_english: "Customers type 'Book a table for 4 on Friday' and it handles everything — no phone calls needed.",
    description: "A conversational reservation manager that eliminates the need for a human host to answer the phone. It handles bookings, sends automated reminders, and manages your waitlist across WhatsApp, SMS, and your website seamlessly. It integrates directly with your existing calendar to prevent double-booking.",
    price: 99,
    category: "chatbot",
    rating: "4.8",
    reviews_count: 412,
    installs_count: 3200,
    setup_time: "Under 5 min",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/booking",
    features: ["Omnichannel WhatsApp & Web widget", "Live Google Calendar & Outlook sync", "Automated SMS/Email reminders", "Intelligent Waitlist management"],
    what_it_does: "Acts as a 24/7 digital host. When a customer messages you asking for a table, the bot checks real-time availability, negotiates times if the requested slot is full, secures the booking, and automatically syncs it to your restaurant's digital calendar.",
    who_its_for: ["Busy restaurants and diners losing customers to missed phone calls", "Trendy cafes and bars needing an automated waitlist system", "Hospitality businesses wanting to modernize their reservation flow"],
    whats_included: ["Floating website booking widget", "Two-way calendar synchronization", "Automated SMS reminder system to reduce no-shows", "Customer database building tool"],
    whats_not_included: ["Carrier SMS sending fees (Twilio/MessageBird)", "Deep integration with legacy, offline POS systems"],
    delivery_info: "Ready to take bookings in under 5 minutes."
  },
  {
    id: "p3",
    title: "WhatsApp Order Automation",
    plain_english: "Customers send their order on WhatsApp, the bot confirms it, takes payment, and notifies your kitchen.",
    description: "A complete end-to-end WhatsApp sales funnel designed specifically for food delivery and retail. From menu browsing and answering product questions to taking the order, processing Stripe payments, and sending a notification straight to your kitchen staff, this bot handles it all without a single human touch.",
    price: 199,
    category: "automation",
    rating: "4.9",
    reviews_count: 655,
    installs_count: 8100,
    setup_time: "Under 5 min",
    status: "active",
    badge: "Top Rated",
    image_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/whatsapp",
    features: ["Official WhatsApp Business API integration", "Native Stripe & PayPal payment links", "Instant Kitchen/Fulfillment notifications", "Conversational support in 50+ languages"],
    what_it_does: "Replaces a human order-taker completely. It showcases your digital menu inside WhatsApp, helps customers customize their orders (e.g., 'no onions, extra cheese'), calculates the total, sends a secure payment link, and routes the confirmed order to your staff's display.",
    who_its_for: ["Cloud kitchens and food delivery services operating on social media", "Local retail stores wanting to sell directly via chat", "Bakeries and custom order businesses"],
    whats_included: ["Approved WhatsApp Business API setup", "Secure payment gateway integration", "Live order management dashboard for staff", "Menu digitization setup"],
    whats_not_included: ["Meta's per-conversation WhatsApp API fees", "Standard Stripe payment processing fees"],
    delivery_info: "Live and ready to take orders in 5 minutes."
  },
  {
    id: "p4",
    title: "Lead Generation Dashboard",
    plain_english: "Captures visitors' contact info from your site and automatically follows up via email and SMS until they buy or book.",
    description: "An AI-powered lead capture and multi-step nurture system. It doesn't just collect emails; it analyzes the visitor's behavior, segments them into the right audience, and triggers hyper-personalized email and SMS sequences that turn cold website traffic into warm, paying customers on autopilot.",
    price: 179,
    category: "marketing",
    rating: "4.8",
    reviews_count: 531,
    installs_count: 4200,
    setup_time: "Under 10 min",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/leads",
    features: ["Smart, high-converting lead capture popups", "AI-written personalized email sequences", "Real-time CRM synchronization", "Automated A/B testing for subject lines"],
    what_it_does: "Acts as a relentless digital sales rep. It captures contact information through beautiful forms, then systematically follows up with leads using AI-generated emails that reference their specific interests until they finally book a call or make a purchase.",
    who_its_for: ["Marketing agencies looking to guarantee ROI for clients", "High-ticket coaches and consultants needing steady calendar bookings", "E-commerce brands building their long-term email lists"],
    whats_included: ["Drag-and-drop lead form builder", "Pre-trained AI email sequence generator", "Advanced conversion analytics dashboard", "Zapier webhooks for easy export"],
    whats_not_included: ["Monthly email sending costs (e.g., SendGrid/Mailgun)", "Advertising spend to drive the initial traffic"],
    delivery_info: "Setup and ready to capture leads in under 10 minutes."
  },
  {
    id: "p5",
    title: "Salon Appointment System",
    plain_english: "Clients book, reschedule or cancel their appointments online anytime — and get automatic reminders so they never forget.",
    description: "A smart, fully automated booking system tailored specifically for salons, spas, and wellness centers. It features AI-powered scheduling that optimizes your calendar to avoid empty gaps, automatic reminders to drastically reduce no-shows, and a comprehensive client management database.",
    price: 89,
    category: "automation",
    rating: "4.9",
    reviews_count: 328,
    installs_count: 2900,
    setup_time: "Under 5 min",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/salon",
    features: ["Beautiful client-facing online booking portal", "Automated SMS & email reminder workflows", "Staff calendar sync & shift management", "Credit card holds for no-show protection"],
    what_it_does: "Takes over the receptionist desk. Clients can view your services, see which stylists are available, book a slot, and securely leave a card on file. The system automatically texts them 24 hours before, allowing them to confirm or reschedule without calling in.",
    who_its_for: ["Hair salons and barbershops needing streamlined scheduling", "Massage spas and wellness centers", "Independent beauty therapists and nail technicians"],
    whats_included: ["Customizable booking widget for your website", "Automated reminder sequence templates", "Internal staff dashboard for daily schedules", "Client history and notes database"],
    whats_not_included: ["Per-message SMS carrier fees", "Custom white-label branding (powered by Deployra branding applies)"],
    delivery_info: "Configured and ready in 5 minutes."
  },
  {
    id: "p6",
    title: "E-commerce AI Sales Assistant",
    plain_english: "A shopping assistant on your store that recommends products, answers questions, and helps customers checkout faster.",
    description: "A highly conversational product recommender and cart recovery agent designed to increase your store's average order value by up to 40%. It acts like an in-store associate, asking shoppers what they are looking for and guiding them to the exact right product in your catalog.",
    price: 129,
    category: "chatbot",
    rating: "4.7",
    reviews_count: 219,
    installs_count: 5600,
    setup_time: "Under 5 min",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/ecom",
    features: ["Intelligent product recommendations", "Automated cart abandonment recovery", "Native Shopify & WooCommerce integration", "Smart upsell and cross-sell automation"],
    what_it_does: "Syncs with your product catalog automatically. If a customer asks 'Do you have red running shoes under $100?', the AI instantly presents a carousel of matching products with add-to-cart buttons directly in the chat interface.",
    who_its_for: ["Shopify and WooCommerce store owners", "Direct-to-consumer (DTC) fashion and lifestyle brands", "Stores with large catalogs where customers get overwhelmed"],
    whats_included: ["Floating chat widget", "Real-time product catalog synchronization", "Sales attribution and analytics dashboard", "Pre-built cart recovery workflows"],
    whats_not_included: ["Fully bespoke widget design", "Shopify Plus enterprise specific features"],
    delivery_info: "Instant setup and catalog sync."
  },
  {
    id: "p7",
    title: "HR Recruitment Screener",
    plain_english: "Paste a job description and it automatically screens CVs, scores candidates and books interviews — saving you hours.",
    description: "An advanced AI recruitment pipeline that takes the manual labor out of hiring. It ingests thousands of resumes, intelligently screens them against your specific job requirements, ranks candidates objectively, and automatically emails top candidates to schedule first-round interviews.",
    price: 249,
    category: "automation",
    rating: "4.8",
    reviews_count: 144,
    installs_count: 1800,
    setup_time: "Under 15 min",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/hr",
    features: ["Unbiased AI CV scoring and ranking", "Automated interview calendar scheduling", "Instant Slack notifications for top-tier applicants", "Seamless integration with popular ATS platforms"],
    what_it_does: "Automates the most tedious parts of hiring. Instead of reading 500 resumes, HR simply logs into the dashboard to see the top 10 candidates already scored out of 100, with interviews already booked on the hiring manager's calendar.",
    who_its_for: ["Overwhelmed HR teams and internal recruiters", "Fast-scaling startups hiring multiple roles", "Recruitment agencies wanting to process talent faster"],
    whats_included: ["Resume parsing and screening engine", "Automated candidate communication bot", "Centralized applicant tracking dashboard", "Interview scheduling links"],
    whats_not_included: ["Paid background checks", "Integration with legacy, custom-built ATS software"],
    delivery_info: "Live and ready to screen in 15 minutes."
  },
  {
    id: "p8",
    title: "Real Estate Lead Qualifier",
    plain_english: "Website visitors answer a few questions and the AI figures out if they're serious buyers — and books a call automatically.",
    description: "An intelligent property inquiry handler that works around the clock. It greets visitors, qualifies them based on budget, timeline, and pre-approval status, answers detailed questions about specific property listings, and books viewings directly into the agent's calendar.",
    price: 159,
    category: "chatbot",
    rating: "4.9",
    reviews_count: 187,
    installs_count: 2100,
    setup_time: "Under 5 min",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/realestate",
    features: ["Dynamic lead qualification question flows", "Property-specific Q&A bot (reads MLS data)", "Direct calendar booking for viewings", "Instant lead export to real estate CRMs"],
    what_it_does: "Separates the window-shoppers from the serious buyers. By having a natural conversation, it gathers exactly what the buyer is looking for. If they meet your criteria, it instantly offers them available times to tour the property.",
    who_its_for: ["Busy estate agents who can't answer the phone 24/7", "Property developers launching new housing projects", "Letting agencies dealing with high-volume rental inquiries"],
    whats_included: ["Lead qualification chatbot", "Viewing calendar booking system", "CRM synchronization (HubSpot, Salesforce, etc.)", "Daily summary reports of new leads"],
    whats_not_included: ["Custom integrations with closed, proprietary MLS data feeds"],
    delivery_info: "Instant deployment."
  },
  {
    id: "p9",
    title: "Social Media Auto-Poster",
    plain_english: "Tell it your brand and it writes and posts content to Instagram, LinkedIn and Twitter — every single day, automatically.",
    description: "A complete AI content engine that puts your social media on autopilot. It learns your brand voice, generates engaging, context-aware text posts, creates relevant hashtags, and publishes them across all major platforms based on an algorithmically optimized schedule.",
    price: 79,
    category: "marketing",
    rating: "4.6",
    reviews_count: 402,
    installs_count: 9800,
    setup_time: "Under 5 min",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1611926653458-09294b3142bf?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/social",
    features: ["Simultaneous multi-platform publishing", "AI-driven caption and hook writer", "Automated hashtag optimization", "Predictive best-time-to-post scheduling"],
    what_it_does: "Eliminates the need for a junior social media manager. You simply input a few topics or URLs, and the AI drafts a month's worth of highly engaging LinkedIn posts, tweets, and Instagram captions, queues them up, and posts them for you.",
    who_its_for: ["Small business owners with no time for marketing", "Content creators looking to maintain consistency", "Marketing teams needing to scale their organic reach"],
    whats_included: ["Multi-platform scheduling calendar", "Unlimited AI caption generation", "Engagement analytics tracking", "Content approval workflow dashboard"],
    whats_not_included: ["Paid advertising management", "AI image generation credits (text/captions only)"],
    delivery_info: "Connect your accounts and start posting in minutes."
  },
  {
    id: "p10",
    title: "Inventory Demand Forecaster",
    plain_english: "It looks at your past sales and tells you exactly what to reorder and when — so you never run out or overstock.",
    description: "A highly sophisticated neural forecasting engine that analyzes historical sales data, seasonality, and market trends to predict future product demand with up to 96% accuracy. It automatically generates purchase orders exactly when you need them.",
    price: 299,
    category: "analytics",
    rating: "4.9",
    reviews_count: 98,
    installs_count: 780,
    setup_time: "Under 20 min",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/inventory",
    features: ["Machine-learning demand forecasting", "Automated Purchase Order (PO) generation", "Native Shopify & WooCommerce sync", "Low-stock supplier SMS/Email alerts"],
    what_it_does: "Stops you from losing money on dead stock or stockouts. It continuously monitors your sell-through rate. When it calculates that you will run out of 'Blue T-shirts (Size M)' in 14 days, it automatically drafts an email to your supplier to reorder the exact optimal quantity.",
    who_its_for: ["Rapidly growing E-commerce brands", "Traditional brick-and-mortar retailers", "Wholesale distributors managing hundreds of SKUs"],
    whats_included: ["Advanced forecasting model", "Purchase order automation engine", "Visual inventory analytics dashboard", "Supplier contact management"],
    whats_not_included: ["Custom integration with complex, legacy ERP systems (e.g., SAP)"],
    delivery_info: "Connected and analyzing your data in 20 minutes."
  },
  {
    id: "p11",
    title: "SEO Content Generator",
    plain_english: "Give it a keyword and it writes a full SEO-optimised blog post that ranks on Google — no writer needed.",
    description: "A GPT-4o powered content engine built specifically for organic search growth. It doesn't just write text; it researches the top-ranking competitors for your keyword, structures a perfect outline, and produces long-form, rank-ready content complete with proper HTML tags and schema markup.",
    price: 59,
    category: "marketing",
    rating: "4.7",
    reviews_count: 712,
    installs_count: 14000,
    setup_time: "Under 5 min",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/seo",
    features: ["Long-form comprehensive blog generation", "Automatic FAQ & Schema markup creation", "Smart internal link suggestions", "1-click WordPress publishing integration"],
    what_it_does: "Acts as your in-house SEO agency. You type in 'Best running shoes 2024', and within two minutes, it delivers a 2,000-word, highly engaging, fully formatted article that is scientifically structured to satisfy Google's search algorithms.",
    who_its_for: ["Affiliate bloggers scaling content production", "SEO agencies managing multiple client sites", "SaaS companies building out their inbound marketing engines"],
    whats_included: ["Unlimited content writer", "On-page SEO audit checker", "Direct CMS publisher tool", "Competitor keyword analyzer"],
    whats_not_included: ["Manual human proofreading", "Off-page backlink building services"],
    delivery_info: "Generate your first ranking post in under 2 minutes."
  },
  {
    id: "p12",
    title: "Analytics & Reports AI",
    plain_english: "Connect your store or app and get a plain-English weekly report: what's working, what's not, and what to fix.",
    description: "A business intelligence agent that takes the confusion out of data. Instead of staring at complex graphs, this AI monitors your critical KPIs daily and delivers simple, actionable weekly insights directly to your inbox or Slack channel, explaining exactly what is happening in your business.",
    price: 119,
    category: "analytics",
    rating: "4.8",
    reviews_count: 231,
    installs_count: 3400,
    setup_time: "Under 10 min",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/analytics",
    features: ["24/7 automated KPI monitoring", "Weekly plain-English executive reports", "Instant anomaly and drop-off alerts", "Direct Slack, Teams, & email delivery"],
    what_it_does: "Turns data into decisions. If your website conversion rate drops by 15% on a Tuesday, the AI immediately messages you on Slack saying: 'Heads up, conversions are down 15% today, likely due to increased bounce rates on mobile devices. Consider checking your mobile checkout page.'",
    who_its_for: ["Non-technical Founders and CEOs", "Marketing managers needing to prove ROI", "Operations teams tracking daily performance"],
    whats_included: ["Centralized metric dashboard", "Automated weekly PDF/Email reports", "Real-time anomaly alert system", "Unlimited data source connections (Stripe, GA4, Shopify)"],
    whats_not_included: ["Building entirely custom data warehouses from scratch"],
    delivery_info: "Connect your apps and get your first report in 10 minutes."
  }
];

export const MOCK_CUSTOM_SOLUTIONS = [
  {
    id: "c1",
    title: "AI-Powered Business Website",
    plain_english: "We build you a beautiful, fast website that has a chatbot built in. Visitors can ask questions and even book or buy — all from one page.",
    description: "A completely custom, conversion-optimised web presence built from the ground up with an embedded AI assistant. We handle the design, the coding, the copywriting, and the training of a custom AI model that lives natively on the site, allowing visitors to instantly get answers, book meetings, or make purchases without leaving the page.",
    category: "website",
    status: "active",
    price_min: 299,
    price_max: 799,
    rating: "4.9",
    installs_count: "342",
    delivery_days: 3,
    developer_name: "WebMind AI Lab",
    image_url: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/custom-web",
    what_it_does: "Replaces an outdated, static website with a dynamic, highly interactive AI-powered machine. We don't just build the site; we train an AI on your specific business rules so it acts as your best salesperson, actively converting visitors into revenue.",
    who_its_for: ["Small businesses needing a modern digital overhaul", "Freelancers and consultants wanting to automate bookings", "Startups looking for a high-tech, premium brand image"],
    whats_included: ["Custom UI/UX website design", "Trained AI chatbot integration", "Foundational Technical SEO setup", "100% Mobile responsive development", "Lightning-fast hosting configuration"],
    whats_not_included: ["Ongoing monthly hosting costs", "Custom domain name purchasing"],
    customization_options: ["Brand colors and typography", "Custom multi-step forms", "Direct calendar booking integration"],
    features: ["Embedded AI Chat", "Ultra-Fast Loading", "SEO Optimized", "Mobile First Design"]
  },
  {
    id: "c2",
    title: "WhatsApp Business Automation",
    plain_english: "We set up a WhatsApp number for your business that automatically handles orders, bookings and customer queries — 24/7.",
    description: "A completely bespoke WhatsApp automation setup tailored to your exact operational workflows. Our engineers map out your customer journey and build custom conversational flows, integrating secure payment gateways, databases, and notifications so your business can operate entirely via chat.",
    category: "automation",
    status: "active",
    price_min: 199,
    price_max: 499,
    rating: "4.9",
    installs_count: "521",
    delivery_days: 2,
    developer_name: "FlowBot Studio",
    image_url: "https://images.unsplash.com/photo-1611746872915-64382b5c76da?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/custom-wa",
    what_it_does: "Turns WhatsApp into an automated storefront or customer service center. We build custom logic so that if a customer asks for a refund, books a specific service, or orders a complex custom product, the bot handles the entire transaction flawlessly.",
    who_its_for: ["Restaurants and cloud kitchens relying on chat orders", "Retailers selling directly to consumers on social media", "Service businesses needing an easy way for clients to book"],
    whats_included: ["Official Meta WhatsApp API setup and verification", "Custom conversation flow design and build", "Stripe/PayPal integration for in-chat payments", "A centralized dashboard for human agents to take over if needed"],
    whats_not_included: ["Meta's ongoing API usage fees per conversation"],
    customization_options: ["Digital menu or service list upload", "Complex conditional booking rules", "Specific payment gateway connections"],
    features: ["24/7 Operations", "In-Chat Payments", "Bespoke Logic Flows", "Multi-agent Dashboard"]
  },
  {
    id: "c3",
    title: "Custom Lead Generation System",
    plain_english: "We build a system that finds potential customers online, contacts them automatically, and books meetings in your calendar.",
    description: "An elite, end-to-end outbound sales pipeline built exactly for your high-ticket offer. We configure AI prospecting tools to scrape targeted leads, write highly personalized cold outreach sequences, and set up automated follow-ups that push interested prospects directly to your booking link.",
    category: "marketing",
    status: "active",
    price_min: 399,
    price_max: 999,
    rating: "4.8",
    installs_count: "178",
    delivery_days: 5,
    developer_name: "ConvertLogic",
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/custom-leads",
    what_it_does: "Acts as a fully automated Sales Development Representative (SDR). We set up the infrastructure so it legally scrapes qualified emails, analyzes their company data, and sends them hyper-customized emails that actually get replies, resulting in booked meetings while you sleep.",
    who_its_for: ["B2B SaaS companies and Enterprise service providers", "Marketing and advertising agencies needing more clients", "High-ticket coaches and specialized consultants"],
    whats_included: ["Lead scraping and prospecting infrastructure setup", "AI-driven cold email sequence copywriting", "Calendar booking integration", "Full synchronization with your existing CRM"],
    whats_not_included: ["Paid advertising spend", "Cost of purchasing sending domains and Google Workspace accounts"],
    customization_options: ["Specific target industry scraping", "Adjustable message tone and angle", "Specific offer and CTA type"],
    features: ["AI Prospecting", "Automated Outreach", "Meeting Booking", "CRM Synchronization"]
  },
  {
    id: "c4",
    title: "Salon & Spa Management System",
    plain_english: "A complete digital system for your salon — online booking, staff schedules, client history, and automatic reminders all in one place.",
    description: "A tailored, comprehensive digital management platform specifically engineered for your salon or spa's unique workflow. We build out a custom online booking portal, configure complex staff rostering, set up a secure client CRM with medical/styling history, and implement automated SMS follow-ups.",
    category: "automation",
    status: "active",
    price_min: 299,
    price_max: 699,
    rating: "4.8",
    installs_count: "156",
    delivery_days: 4,
    developer_name: "Gastronomic AI Core",
    image_url: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/custom-salon",
    what_it_does: "Completely digitizes operations. We configure the system so that when 'Stylist A' takes a vacation, her slots disappear. When a VIP client books, the system notes their preferred drink. It handles all the logistics so your staff can focus purely on the service.",
    who_its_for: ["Multi-staff hair salons and premium barbershops", "High-end luxury spas and wellness retreats", "Aesthetic clinics and beauty studios"],
    whats_included: ["White-labeled client booking portal", "Comprehensive staff schedule dashboard", "Secure client CRM with notes/history", "Automated SMS/Email reminder configuration"],
    whats_not_included: ["Physical hardware (tablets, registers)", "Ongoing SMS carrier costs"],
    customization_options: ["Detailed service menu building", "Granular staff permissions and roles", "Full brand color and logo integration"],
    features: ["Custom Online Booking", "Advanced Staff Scheduling", "Detailed Client CRM", "Automated Reminders"]
  },
  {
    id: "c5",
    title: "Restaurant Ordering & Kitchen System",
    plain_english: "Customers scan a QR code, order from their phone, pay instantly — and the kitchen gets the order on a screen automatically.",
    description: "A completely bespoke digital ordering ecosystem tailored to your restaurant's physical layout and menu. We design beautifully branded QR code menus, configure secure instant payment processing, and set up a live Kitchen Display System (KDS) so orders flow seamlessly from table to chef without a waiter.",
    category: "automation",
    status: "active",
    price_min: 499,
    price_max: 1199,
    rating: "4.9",
    installs_count: "89",
    delivery_days: 7,
    developer_name: "TableTech AI",
    image_url: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/custom-restaurant",
    what_it_does: "Speeds up table turnover and increases order size. We build the exact menu hierarchy with all modifiers (e.g., 'extra spicy', 'no mayo'). Customers order and pay on their phones, and the order instantly pops up on a digital screen in your kitchen, completely eliminating manual order entry errors.",
    who_its_for: ["Fast-casual restaurants and busy cafes", "Large food courts and multi-vendor spaces", "Pubs and bars wanting to reduce queue times"],
    whats_included: ["Custom branded QR digital menu system", "Cloud-based Kitchen Display System setup", "Secure payment gateway integration", "Live order management and revenue dashboard"],
    whats_not_included: ["Physical hardware like iPads or receipt printers", "Standard transaction fees from payment processors"],
    customization_options: ["Bespoke menu design and photography upload", "Custom UI category layout", "Specific receipt printer routing"],
    features: ["QR Table Ordering", "Live Kitchen Display", "Instant Payments", "Real-time Order Tracking"]
  },
  {
    id: "c6",
    title: "E-commerce Store with AI",
    plain_english: "We build you a full online shop with an AI assistant that helps customers find products, answers questions, and recovers abandoned carts.",
    description: "A premium, fully custom e-commerce storefront engineered for maximum conversions. We build the site using modern frameworks (Shopify or Next.js), professionally design the layout, upload your catalog, and embed a proprietary AI shopping assistant trained exclusively on your brand's voice and products.",
    category: "website",
    status: "active",
    price_min: 599,
    price_max: 1499,
    rating: "4.8",
    installs_count: "203",
    delivery_days: 7,
    developer_name: "ShopMind Builders",
    image_url: "https://images.unsplash.com/photo-1556742208-999815fca738?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/custom-ecom",
    what_it_does: "Creates a high-end digital flagship store. We ensure the site loads instantly and looks stunning on mobile. The integrated AI proactively messages shoppers, offering personalized style advice or technical specs, dramatically reducing bounce rates and cart abandonment.",
    who_its_for: ["Direct-to-consumer product brands scaling up", "Independent artists and creators launching merch", "Traditional retailers moving online for the first time"],
    whats_included: ["Complete storefront design and development", "Custom-trained AI shopping assistant", "Payment gateway and shipping rule setup", "Advanced Google/Meta analytics tracking"],
    whats_not_included: ["Professional product photography", "Monthly Shopify or server hosting fees"],
    customization_options: ["Premium brand design and typography", "Custom product filtering categories", "Tailored multi-step checkout flow"],
    features: ["Trained AI Assistant", "Automated Cart Recovery", "Smart Upsell Engine", "Deep Analytics"]
  },
  {
    id: "c7",
    title: "Private Company Knowledge Bot",
    plain_english: "Upload all your company documents and your team can ask it any question — and it answers instantly with the right information.",
    description: "A highly secure, bespoke private AI assistant built specifically for your enterprise. We ingest your proprietary company documents, standard operating procedures, manuals, and HR policies into an isolated, secure vector database, creating a custom AI that serves as an instant 'second brain' for your entire workforce.",
    category: "chatbot",
    status: "active",
    price_min: 799,
    price_max: 1999,
    rating: "5.0",
    installs_count: "41",
    delivery_days: 5,
    developer_name: "Neural Nexus Enterprise",
    image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/custom-knowledge",
    what_it_does: "Eliminates hours wasted searching for files. An employee can simply type: 'What is our policy on remote work expenses?' and the AI instantly generates a summary, providing a direct link to page 14 of the official HR handbook. We build strict access controls so only authorized roles see sensitive data.",
    who_its_for: ["Law firms with massive case document archives", "Corporate HR departments handling repetitive policy questions", "Large enterprises with complex internal wikis"],
    whats_included: ["Secure document ingestion and vectorization", "Deployment of a private, isolated AI model", "Custom web portal for employees to chat", "Enterprise-grade Role-Based Access Controls (RBAC)"],
    whats_not_included: ["Air-gapped, on-premise physical server hosting"],
    customization_options: ["Detailed access roles and permissions", "Custom data source connections (Google Drive, Notion)", "Internal UI branding and naming"],
    features: ["100% Private & Secure", "Accurate Source Citations", "Strict Access Controls", "Supports Any Document Type"]
  },
  {
    id: "c8",
    title: "Financial Anomaly Detector",
    plain_english: "It watches every transaction in your accounts and immediately alerts you if anything looks wrong — like duplicate payments or unusual spending.",
    description: "A custom-configured AI financial watchdog that integrates directly with your accounting software (Xero, QuickBooks, etc.). We program the AI to understand your business's normal spending patterns so it can automatically flag duplicate invoices, unusual vendor payments, or sudden spikes in expenses in real time.",
    category: "analytics",
    status: "active",
    price_min: 399,
    price_max: 999,
    rating: "4.9",
    installs_count: "88",
    delivery_days: 4,
    developer_name: "QuantSafe AI",
    image_url: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/custom-finance",
    what_it_does: "Prevents financial leaks before they impact cash flow. We set up custom rules so that if a $500 software subscription is accidentally billed twice, the AI immediately sends an urgent Slack alert to the CFO, complete with transaction IDs and a link to dispute the charge.",
    who_its_for: ["CFOs and financial controllers managing high transaction volumes", "Accountants wanting to provide proactive alerts to clients", "Startups with rapidly fluctuating operating expenses"],
    whats_included: ["Direct Xero/QuickBooks API integration", "Custom alerting system (Slack/Teams/Email)", "Live financial monitoring dashboard", "Automated weekly health-check reports"],
    whats_not_included: ["Certified legal or tax filing advice"],
    customization_options: ["Granular anomaly alert thresholds", "Custom report frequency and format", "Specific vendor whitelisting rules"],
    features: ["Real-time Transaction Monitoring", "Fraud & Error Detection", "Automated Executive Reports", "AI Receipt Parsing"]
  },
  {
    id: "c9",
    title: "Social Media Content Agency Bot",
    plain_english: "We build you an AI that writes, designs and schedules all your social posts — like having a full social media manager for a fraction of the cost.",
    description: "A completely bespoke AI content production pipeline built around your brand identity. We don't just provide software; we prompt-engineer the AI to perfectly mimic your brand's unique tone of voice, integrate it with custom graphic design templates, and establish an automated approval and publishing schedule.",
    category: "marketing",
    status: "active",
    price_min: 249,
    price_max: 599,
    rating: "4.7",
    installs_count: "215",
    delivery_days: 3,
    developer_name: "StudioFusion",
    image_url: "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/custom-social",
    what_it_does: "Acts as your in-house creative agency. We set up the pipeline so that when you feed it a single blog post or idea, the system automatically generates a LinkedIn thought-leadership post, an Instagram carousel with branded graphics, and a Twitter thread, all queued up for approval.",
    who_its_for: ["Personal brands and thought leaders", "Marketing agencies looking to scale content for clients", "Solo-entrepreneurs who lack the time to post daily"],
    whats_included: ["Bespoke AI tone-of-voice training", "Automated multi-platform scheduler setup", "Integration with your custom graphic templates", "Comprehensive engagement analytics tracking"],
    whats_not_included: ["Paid ad campaign management", "Third-party platform API fees if volume is massive"],
    customization_options: ["Highly specific brand voice engineering", "Custom posting frequency strategies", "Selection of niche platforms"],
    features: ["Trained AI Copywriting", "Fully Automated Posting", "100% Brand Consistent", "Multi-platform Distribution"]
  },
  {
    id: "c10",
    title: "Clinic Patient Management System",
    plain_english: "Patients book online, fill forms digitally, get reminders — and your clinic gets a clean dashboard showing all appointments and patient history.",
    description: "A HIPAA/GDPR-compliant, custom-built patient management portal tailored to your specific clinical workflows. We digitalize your entire intake process—from online appointment booking and secure digital consent forms, to automated SMS appointment reminders and a centralized practitioner dashboard.",
    category: "automation",
    status: "active",
    price_min: 599,
    price_max: 1299,
    rating: "4.9",
    installs_count: "67",
    delivery_days: 7,
    developer_name: "HealthStack AI",
    image_url: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80","https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"],
    demo_url: "https://example.com/demo/custom-clinic",
    what_it_does: "Modernizes the patient experience and eliminates front-desk paperwork. We build custom digital intake forms that automatically update the patient's secure file before they even arrive. The system automatically handles reminders, significantly reducing costly missed appointments.",
    who_its_for: ["Private medical clinics and general practices", "Physical therapists and chiropractors", "Dental offices and specialized health centers"],
    whats_included: ["Secure patient online booking portal", "Custom digital intake and consent forms", "Encrypted patient medical records database", "Automated SMS/Email reminder system"],
    whats_not_included: ["Direct integration with government medical billing networks", "Physical clinic hardware"],
    customization_options: ["Highly detailed custom medical intake forms", "Specific practitioner and service type routing", "Custom clinical role permissions"],
    features: ["Secure Online Booking", "Digital Intake Workflows", "Automated SMS Reminders", "Encrypted Patient History"]
  }
];
